version: '3'

networks:
  datascout-api-network:

services:

  php:
    build:
      context: ./docker/php
    container_name: datascout-api-php
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/app
    ports:
      - '9000:9000'
    networks:
      - datascout-api-network

  nginx:
    image: nginx:stable-alpine
    container_name: datascout-api-nginx
    ports:
      - '80:80'
    volumes:
      - ./symfony/:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    depends_on:
      - php
      - database
    networks:
      - datascout-api-network

  database:
    image: mysql:8
    container_name: datascout-api-database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    networks:
      - datascout-api-network

  rabbitmq: # The RabbitMQ container.
    container_name: datascout-api-rabbitmq
    build:
      context: ./docker/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq:cached
    networks:
      - datascout-api-network